---
abstract: 'Bitcard authentication verification'
author:
  - 'Ask Bjørn Hansen <ask@develooper.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authen-Bitcard
requires:
  Class::ErrorHandler: 0
  Digest::SHA: 0
  HTTP::Status: 0
  JSON: 2.12
  LWP::UserAgent: 0
  MIME::Base64: 0
  Math::BigInt: 0
  URI: 1.22
resources:
  homepage: http://search.cpan.org/dist/Authen-Bitcard/
  repository: http://git.develooper.com/bitcard-perl-api.git
version: 0.89
