--- #YAML:1.0
name: Authen-Bitcard
version: 0.85
author:
  - Ask Bjoern Hansen <ask@develooper.com>
abstract: Bitcard authentication verification
license: open_source
generated_by: Module::Build version 0.2611, without YAML.pm
